### ISSUE TITLE
FR: vim-like keymap

### ISSUE THREAD

**Issue by mwoz123** [Haeri/monolith-code#26]
is there a chance for vim-like keymappings ? 

Thanks
mwoz

**Comment by Haeri** [comment]
Yes, this is very much possible. I'm using the [ace editor](https://ace.c9.io/build/kitchen-sink.html) which allows for different key mappings. I would just need to figure out how to best expose those settings in the app.

**Comment by Haeri** [comment]
In fact, what you can do is press `ctrl + shift + i` to open up the chrome dev tool and type `editor.setKeyboardHandler("ace/keyboard/vim");` into the console. This will enable vim controls. Obviously, OS operations are not set up but at least you should be able to perform the usual editing operations within the editor.

**Comment by mwoz123** [comment]
Awesome news:) 
how about creating keymap.js config file and exposing editor property so it set to vim keymap?
