### ISSUE TITLE
A Small Help

### ISSUE THREAD

**Issue by solomonshalom** [Haeri/monolith-code#32]
Shalom!

Love the editor, but in my exploration of Monolith Code 2, I wasn't able to open the in-built terminal, how do I do that?

God Bless!

**Comment by Haeri** [comment]
Hi @solomonshalom 

Check out this issue here: https://github.com/Haeri/monolith-code/issues/29

Best regards,
Haeri

**Comment by solomonshalom** [comment]
Shalom! @Haeri 

Ah! Thanks!

I was thinking if there could be a short-cut assigned to it, it would be really helpfull!

God Bless!
Solomon Shalom Lijo

**Comment by Haeri** [comment]
I've added `ctrl + shift + x` to toggle the console. I have also added all the available shortcuts to the [website](https://haeri.github.io/monolith-code/).

Regarding the current directory, the console already shows the current directory whenever you open or save a file.

**Comment by solomonshalom** [comment]
Ah, Thanks!

**Comment by Haeri** [comment]
All good, I added the instructions after you asked so it wasn't there before.

Feel free to close this issue if everything is resolved.

Best,
Haeri

**Comment by solomonshalom** [comment]
> All good, I added the instructions after you asked so it wasn't there before.
> 
> Feel free to close this issue if everything is resolved.
> 
> Best, Haeri

Shalom! @Haeri,

I see! that's nice and Yep, it's resolved!

Thank you so much for helping me out! Mate
